### PR TITLE
[#11] Add wiki page and AWS infrastructure diagram

### PR DESCRIPTION
**Pull request by liamstevens111**
- #11 

## What happened 👀

Initial infrastructure diagram for AWS 

## Insight 📝

The requirements state the database should be in high availability mode so I have chosen Multi-AZ deployment which has a standby secondary instance. I haven't included any additional `read replicas` and this is a separate topic I think as well.

## Proof Of Work 📹

In the Files Changed tab which shows the markdown file and diagram

### CODE REVIEW

**Comment by andyduong1920** [comment]
1/ Are we using AWS Route 53?, you will bough some real domain @liamstevens111 is it in the IC requirement :D 
2/ The ElastiCache should be in the Private network scope as well ;)  
3/ Will you use CloudWatch Log?
4/ Will you use SSM or KMS for the sensitive key, I don't see it on the diagram.
5/ Will you plan to create a Bastion host in order to allow the user can connect to the Database for debugging the data or SSH into the Fargate later, this is a low-priority task, FYI
6/ I hear we mention the auto-scaling, I don't see that component on the diagram, will we create that component?

**Comment by liamstevens111** [comment]
@andyduong1920 

1. I haven't looked into too much detail but can't we just create a subdomain? If not then it's fine I will just use the ALB domain name
2. The diagram shows Elasticache in private subnetwork
3. I will, defined in ECS definition, do you want me to create a separate issue for that? Don't know if used for alarm as well to scale based upon users
4. SSM has parameter store which uses KMS. Do you mean Parameter Store or Secrets Manager? If it's just DB credentials I will use Parameter Store as it's also free.
5. No I will not as not on the requirements unless I have missed it
6. I will the autoscaling is handled with capacity provider / cloudwatch not an autoscaling module as used with EC2?

**Comment by andyduong1920** [comment]
@liamstevens111 

1/ Just use the ALB domain
2/ Is it?

image

3/ CloudWatch for storing the Log of the application, let's me check the IC's requirement again, but think about how to you store and access the log after you deploy the application

4/ Will use Parameter Store, great, let's add it into the diagram @liamstevens111 

5/ It's ok as I just said it's low priority, nice to have and nice to know ;) 

6/ yeah

**Comment by liamstevens111** [comment]
@andyduong1920 

1. Alright to keep it simple we wont use s3, just alb domain as mentioned :) Will remove from diagram
2. The same as I did it on client project diagram - you mean it's outside of the subnet boxes? Ok I can make the boxes taller for clarity 👍  Good spot, it looks like it's floating in the middle of nowhere
3. Don't know what you mean? To store it is to use `Task Role` to submit the logs there?
4. Okay will add to diagram 👍

**Comment by liamstevens111** [comment]
Updated diagram

Screenshot 2022-12-15 at 12 46 54

**Comment by andyduong1920** [comment]
The diagram looks good now @liamstevens111 👍 just 2 concerns

1/ The Terraform Cloud falling

image

Should we fix it on this PR

2/ For the Wiki, I think with this just setup, we won't have it on the https://github.com/liamstevens111/terraform-infrastructure-example/wiki page, you will need to add the `Publish wiki github action` to push these files to Github Wiki ;)

**Comment by liamstevens111** [comment]
@andyduong1920 Will add wiki PR issue if not there already, although not 100% on how to add this yet 👍 

It's failing because the project config is empty ( doesn't exist from the first PR as not merged yet). The repo is empty at the moment 😛

**Comment by andyduong1920** [comment]
> @andyduong1920 Will add wiki PR issue 👍

Ok 👌 

> It's failing because the project config is empty ( doesn't exist from the first PR as not merged yet). The repo is empty at the moment 

Got it @liamstevens111

**Review by andyduong1920 — APPROVED** [review]

**Review by hoangmirs — APPROVED** [review]

**Comment by liamstevens111** [comment]
@andyduong1920 Shall I wait for github action for the Wiki you mentioned before merging this? https://github.com/liamstevens111/terraform-infrastructure-example/pull/18#issuecomment-1358809176

**Pull request merged**
